# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vdZnJTFTUyMnKO2AMYaiCH1XFkUvyEDI
"""

import matplotlib.colors as cl
import matplotlib.pyplot as plt
import pandas as pd
import row64
import seaborn as sns

def ScatterPlotBasic(inDf, inCol1, inCol2):
	col1 = inDf.columns[inCol1]
	col2 = inDf.columns[inCol2]
	sns.scatterplot(color="#1F77B4",data=inDf,x=col1,y=col2,s=25)

#IMPORT("C:\Users\bobott\Desktop\sneakers.csv")
dfIn=row64.get_dataframe("Dataframe3")
df=dfIn.copy(deep=True)
ScatterPlotBasic(df,5,15)

import matplotlib.colors as cl
import matplotlib.pyplot as plt
import pandas as pd
import row64
import seaborn as sns

def ScatterPlotBasic(inDf, inCol1, inCol2):
	col1 = inDf.columns[inCol1]
	col2 = inDf.columns[inCol2]
	sns.scatterplot(color="#1F77B4",data=inDf,x=col1,y=col2,s=25)

#IMPORT("C:\Users\bobott\Desktop\sneakers.csv")
dfIn=row64.get_dataframe("Dataframe3")
df=dfIn.copy(deep=True)
ScatterPlotBasic(df,3,15)

import matplotlib.colors as cl
import matplotlib.pyplot as plt
import pandas as pd
import row64
import seaborn as sns

def ScatterPlotBasic(inDf, inCol1, inCol2):
	col1 = inDf.columns[inCol1]
	col2 = inDf.columns[inCol2]
	sns.scatterplot(color="#1F77B4",data=inDf,x=col1,y=col2,s=25)

#IMPORT("C:\Users\bobott\Desktop\sneakers.csv")
dfIn=row64.get_dataframe("Dataframe7")
df=dfIn.copy(deep=True)
ScatterPlotBasic(df,6,15)

